### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by danglingptr0x0** [joshghent/rescue-box#8]
The `Update gist` job has failed with the following:

```
Run joshghent/rescue-box@master
  env:
    GH_TOKEN: ***
    GIST_ID: ***
    RESCUETIME_API_KEY: ***
/usr/bin/docker run --name a33c15bc7819ce34543d388c95c55ea6ac7cc_4cc13f --label 8a33c1 --workdir /github/workspace --rm -e GH_TOKEN -e GIST_ID -e RESCUETIME_API_KEY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/simonSlamka/simonSlamka":"/github/workspace" 8a33c1:5bc7819ce34543d388c95c55ea6ac7cc
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/github/workspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

What's the missing js file? Where can it be found?

All the other jobs report success.

**Comment by joshghent** [comment]
Hey @simonSlamka thanks for raising an issue. 
Did you figure out the issue?
If not, please send me a copy of the entire github action please :)

**Comment by danglingptr0x0** [comment]
Yeah, I figured it out, thanks for your response.

The .js script was missing from my repo.
